[
  {"id":1,"name":"Oslo","lat":59.9139,"lng":10.7522,"type":"city","region":"Østlandet","desc":"Hauptstadt Norwegens mit Opernhaus, Vigeland-Park und Festung Akershus.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Oslo_opera_house.jpg/640px-Oslo_opera_house.jpg"},
  {"id":2,"name":"Bergen","lat":60.3913,"lng":5.3221,"type":"city","region":"Vestlandet","desc":"Tor zu den Fjorden – bunte Holzhäuser am Bryggen-Kai, UNESCO-Welterbe.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bergen_bryggen.jpg/640px-Bergen_bryggen.jpg"},
  {"id":3,"name":"Tromsø","lat":69.6492,"lng":18.9553,"type":"city","region":"Nord-Norge","desc":"Nördlichste Großstadt Europas – Nordlichter und Mitternachtssonne.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Tromso_IMG_1890.JPG/640px-Tromso_IMG_1890.JPG"},
  {"id":4,"name":"Trondheim","lat":63.4305,"lng":10.3951,"type":"city","region":"Trøndelag","desc":"Mittelalterliche Stadt mit dem Nidarosdom, gotischer Krönungskathedrale.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Trondheim_montasje.jpg/640px-Trondheim_montasje.jpg"},
  {"id":5,"name":"Stavanger","lat":58.9700,"lng":5.7331,"type":"city","region":"Vestlandet","desc":"Öl-Metropole und Ausgangspunkt zum Preikestolen.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Stavanger_Old_Town.jpg/640px-Stavanger_Old_Town.jpg"},
  {"id":6,"name":"Kristiansand","lat":58.1467,"lng":7.9956,"type":"city","region":"Sørlandet","desc":"Südlichste Großstadt Norwegens, beliebtes Sommerziel.","img":""},
  {"id":7,"name":"Fredrikstad","lat":59.2181,"lng":10.9298,"type":"city","region":"Østlandet","desc":"Besterhaltene Festungsanlage Skandinaviens aus dem 17. Jahrhundert.","img":""},
  {"id":8,"name":"Sandnes","lat":58.8520,"lng":5.7352,"type":"city","region":"Vestlandet","desc":"Zweitgrößte Stadt der Rogaland-Region.","img":""},
  {"id":9,"name":"Drammen","lat":59.7440,"lng":10.2045,"type":"city","region":"Østlandet","desc":"Hafenstadt am Drammenfjord westlich von Oslo.","img":""},
  {"id":10,"name":"Ålesund","lat":62.4722,"lng":6.1549,"type":"city","region":"Vestlandet","desc":"Jugendstil-Stadt auf mehreren Inseln am Atlantik.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Aalesund_edit2.jpg/640px-Aalesund_edit2.jpg"},
  {"id":11,"name":"Geirangerfjord","lat":62.1006,"lng":7.0867,"type":"fjord","region":"Vestlandet","desc":"UNESCO-Welterbe – einer der dramatischsten Fjorde der Welt.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Geiranger_Fjord_%285%29.jpg/640px-Geiranger_Fjord_%285%29.jpg"},
  {"id":12,"name":"Nærøyfjord","lat":60.9167,"lng":6.7167,"type":"fjord","region":"Vestlandet","desc":"UNESCO-Welterbe – schmalster Fjord Norwegens.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Aurland_Sognefjord_2.jpg/640px-Aurland_Sognefjord_2.jpg"},
  {"id":13,"name":"Sognefjord","lat":61.1000,"lng":6.5000,"type":"fjord","region":"Vestlandet","desc":"Längster und tiefster Fjord Norwegens – 204 km lang.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Sognefjord%2C_Norway.jpg/640px-Sognefjord%2C_Norway.jpg"},
  {"id":14,"name":"Hardangerfjord","lat":60.2000,"lng":6.4000,"type":"fjord","region":"Vestlandet","desc":"Zweitlängster Fjord Norwegens, bekannt für Obstblüte.","img":""},
  {"id":15,"name":"Lysefjord","lat":59.0167,"lng":6.4333,"type":"fjord","region":"Vestlandet","desc":"Heimat des berühmten Preikestolen-Felsens.","img":""},
  {"id":16,"name":"Preikestolen","lat":58.9863,"lng":6.1892,"type":"mountain","region":"Vestlandet","desc":"604 m hoher Felsplateau-Aussichtspunkt über dem Lysefjord.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Preikestolen_2014_%28cropped%29.jpg/640px-Preikestolen_2014_%28cropped%29.jpg"},
  {"id":17,"name":"Trolltunga","lat":60.1241,"lng":6.7390,"type":"mountain","region":"Vestlandet","desc":"Dramatischer Felszunge 700 m über dem Ringedalsvatnet.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Trolltunga_%28A_Trolls_tongue%29.jpg/640px-Trolltunga_%28A_Trolls_tongue%29.jpg"},
  {"id":18,"name":"Galdhøpiggen","lat":61.6364,"lng":8.3122,"type":"mountain","region":"Innlandet","desc":"Höchster Berg Norwegens und Skandinaviens – 2.469 m.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Galdhopiggen.jpg/640px-Galdhopiggen.jpg"},
  {"id":19,"name":"Besseggen","lat":61.5167,"lng":8.8667,"type":"mountain","region":"Innlandet","desc":"Berühmter Bergrücken im Jotunheimen, über zwei verschiedenfarbige Seen.","img":""},
  {"id":20,"name":"Stetind","lat":68.1416,"lng":16.5988,"type":"mountain","region":"Nord-Norge","desc":"Norwegens Nationalberg – markanter Granitobelisk in Nordland.","img":""},
  {"id":21,"name":"Lofoten","lat":68.1536,"lng":13.9886,"type":"island","region":"Nord-Norge","desc":"Dramatische Inselgruppe mit Fischerdörfern und Nordlichtern.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Reine%2C_Lofoten%2C_Norway.jpg/640px-Reine%2C_Lofoten%2C_Norway.jpg"},
  {"id":22,"name":"Reine","lat":67.9344,"lng":13.0881,"type":"village","region":"Nord-Norge","desc":"Malerischstes Dorf Norwegen auf den Lofoten.","img":""},
  {"id":23,"name":"Henningsvær","lat":68.1535,"lng":14.1870,"type":"village","region":"Nord-Norge","desc":"Kleines Fischerdorf auf den Lofoten – Kulturzentrum der Inselgruppe.","img":""},
  {"id":24,"name":"Vesterålen","lat":68.8000,"lng":15.0000,"type":"island","region":"Nord-Norge","desc":"Inselgruppe nördlich der Lofoten – Walbeobachtung und Küstenwandern.","img":""},
  {"id":25,"name":"Svalbard","lat":78.2232,"lng":15.6469,"type":"island","region":"Svalbard","desc":"Arktischer Archipel mit Eisbären, Gletschern und Mitternachtssonne.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Longyearbyen_IMG_3822.jpg/640px-Longyearbyen_IMG_3822.jpg"},
  {"id":26,"name":"Longyearbyen","lat":78.2232,"lng":15.6469,"type":"city","region":"Svalbard","desc":"Nördlichste Stadt der Welt mit dauerhafter Bevölkerung.","img":""},
  {"id":27,"name":"Nordkapp","lat":71.1695,"lng":25.7850,"type":"landmark","region":"Nord-Norge","desc":"Nördlichster Punkt Europas – berühmter Aussichtspunkt an der Barentssee.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Nordkapp_%285%29.jpg/640px-Nordkapp_%285%29.jpg"},
  {"id":28,"name":"Hammerfest","lat":70.6634,"lng":23.6821,"type":"city","region":"Nord-Norge","desc":"Eine der nördlichsten Städte der Welt.","img":""},
  {"id":29,"name":"Alta","lat":69.9689,"lng":23.2716,"type":"city","region":"Nord-Norge","desc":"Bekannt für Nordlichter und prähistorische Felszeichnungen (UNESCO).","img":""},
  {"id":30,"name":"Bodø","lat":67.2804,"lng":14.4049,"type":"city","region":"Nord-Norge","desc":"Tor zu den Lofoten – stärkste Gezeitenströmung der Welt: Saltstraumen.","img":""},
  {"id":31,"name":"Saltstraumen","lat":67.2453,"lng":14.6292,"type":"landmark","region":"Nord-Norge","desc":"Stärkster Mahlstrom der Welt – bis zu 37 km/h Strömungsgeschwindigkeit.","img":""},
  {"id":32,"name":"Mo i Rana","lat":66.3126,"lng":14.1429,"type":"city","region":"Nord-Norge","desc":"Polarzirkel-Stadt in Nordland.","img":""},
  {"id":33,"name":"Narvik","lat":68.4384,"lng":17.4270,"type":"city","region":"Nord-Norge","desc":"Wichtiger Erzhafen am Ofotfjord, bekannt aus dem 2. Weltkrieg.","img":""},
  {"id":34,"name":"Harstad","lat":68.7990,"lng":16.5417,"type":"city","region":"Nord-Norge","desc":"Stadt auf Hinnøya, größter Insel Norwegens.","img":""},
  {"id":35,"name":"Sortland","lat":68.6953,"lng":15.4136,"type":"city","region":"Nord-Norge","desc":"Blaue Stadt in Vesterålen.","img":""},
  {"id":36,"name":"Andøya","lat":69.1167,"lng":15.8500,"type":"island","region":"Nord-Norge","desc":"Nördlichste Insel Vesterålens – Rakettenabschussbasis und Walbeobachtung.","img":""},
  {"id":37,"name":"Senja","lat":69.3000,"lng":17.4000,"type":"island","region":"Nord-Norge","desc":"Zweitgrößte Insel Norwegens – wilder als die Lofoten.","img":""},
  {"id":38,"name":"Husøy","lat":69.6519,"lng":17.0481,"type":"village","region":"Nord-Norge","desc":"Kleines Fischerdorf auf Senja.","img":""},
  {"id":39,"name":"Skjervøy","lat":70.0383,"lng":20.9756,"type":"village","region":"Nord-Norge","desc":"Fischerinsel in Troms – Walbeoabachtung im Winter.","img":""},
  {"id":40,"name":"Kjøpsvik","lat":68.1064,"lng":16.3819,"type":"village","region":"Nord-Norge","desc":"Kleiner Ort am Tysfjord, einem der tiefsten Fjorde Norwegens.","img":""},
  {"id":41,"name":"Jotunheimen","lat":61.5833,"lng":8.5000,"type":"nationalpark","region":"Innlandet","desc":"Nationalpark der Riesen – höchste Gebirgsregion Norwegens.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Jotunheimen_in_summer.jpg/640px-Jotunheimen_in_summer.jpg"},
  {"id":42,"name":"Hardangervidda","lat":60.1167,"lng":7.5000,"type":"nationalpark","region":"Vestlandet","desc":"Europas größtes Hochplateau – Rentierwanderungen und Polarfuchse.","img":""},
  {"id":43,"name":"Dovrefjell","lat":62.3167,"lng":9.5667,"type":"nationalpark","region":"Innlandet","desc":"Heimat der Moschusochsen – Nationalpark mit arktischer Hochgebirgslandschaft.","img":""},
  {"id":44,"name":"Jæren","lat":58.7500,"lng":5.5833,"type":"landmark","region":"Vestlandet","desc":"Flache Küstenlandschaft in Rogaland – Dünen und Strände.","img":""},
  {"id":45,"name":"Flåm","lat":60.8635,"lng":7.1131,"type":"village","region":"Vestlandet","desc":"Ausgangspunkt der Flåmsbahn – eine der steilsten Bahnstrecken der Welt.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Flam_village_%28edited%29.jpg/640px-Flam_village_%28edited%29.jpg"},
  {"id":46,"name":"Flåmsbahn","lat":60.8635,"lng":7.1131,"type":"landmark","region":"Vestlandet","desc":"20 km lange Bahnstrecke durch spektakuläre Gebirgslandschaft.","img":""},
  {"id":47,"name":"Voss","lat":60.6280,"lng":6.4179,"type":"city","region":"Vestlandet","desc":"Abenteuersport-Hauptstadt Norwegens – Fallschirm, Rafting, Ski.","img":""},
  {"id":48,"name":"Eidfjord","lat":60.4683,"lng":7.0728,"type":"village","region":"Vestlandet","desc":"Am Ende des Eidfjords – Vøringsfossen-Wasserfall in der Nähe.","img":""},
  {"id":49,"name":"Vøringsfossen","lat":60.4200,"lng":7.2167,"type":"landmark","region":"Vestlandet","desc":"Norwegens bekanntester Wasserfall – 182 m freier Fall.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Voeringsfoss_1.jpg/640px-Voeringsfoss_1.jpg"},
  {"id":50,"name":"Åndalsnes","lat":62.5722,"lng":7.6874,"type":"city","region":"Vestlandet","desc":"Tor zur Romsdalsfjord-Region und dem Trollstigen.","img":""},
  {"id":51,"name":"Trollstigen","lat":62.4561,"lng":7.6686,"type":"landmark","region":"Vestlandet","desc":"Legendäre Serpentinenstraße mit 11 Haarnadelkurven.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Trollstigen_2012.jpg/640px-Trollstigen_2012.jpg"},
  {"id":52,"name":"Atlantikstraße","lat":63.0120,"lng":7.3394,"type":"landmark","region":"Vestlandet","desc":"Berühmteste Küstenstraße Norwegens über 8 Brücken.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Atlanterhavsveien.jpg/640px-Atlanterhavsveien.jpg"},
  {"id":53,"name":"Kristiansund","lat":63.1107,"lng":7.7279,"type":"city","region":"Vestlandet","desc":"Klippfisch-Hauptstadt Norwegens auf vier Inseln.","img":""},
  {"id":54,"name":"Molde","lat":62.7375,"lng":7.1591,"type":"city","region":"Vestlandet","desc":"Rosenstadt am Romsdalsfjord mit Panoramaaussicht.","img":""},
  {"id":55,"name":"Hjørundfjord","lat":62.1000,"lng":6.2000,"type":"fjord","region":"Vestlandet","desc":"Einer der schönsten und wildesten Fjorde der Sunnmøre-Region.","img":""},
  {"id":56,"name":"Ørsta","lat":62.1997,"lng":6.1344,"type":"city","region":"Vestlandet","desc":"Tor zum Hjørundfjord und dem Sunnmøre-Gebirge.","img":""},
  {"id":57,"name":"Volda","lat":62.1481,"lng":6.0739,"type":"city","region":"Vestlandet","desc":"Hochschulstadt im Sunnmøre-Fjordland.","img":""},
  {"id":58,"name":"Stryn","lat":61.9044,"lng":6.7225,"type":"city","region":"Vestlandet","desc":"Bekannt für Gletscherwanderungen am Jostedalsbreen.","img":""},
  {"id":59,"name":"Jostedalsbreen","lat":61.7000,"lng":7.0000,"type":"nationalpark","region":"Vestlandet","desc":"Größter Gletscher Kontinentaleuropas – 487 km².","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Jostedalsbreen.jpg/640px-Jostedalsbreen.jpg"},
  {"id":60,"name":"Nigardsbreen","lat":61.6944,"lng":7.2025,"type":"landmark","region":"Vestlandet","desc":"Zugänglichster Arm des Jostedalsbreen-Gletschers.","img":""},
  {"id":61,"name":"Fjærland","lat":61.4167,"lng":6.7500,"type":"village","region":"Vestlandet","desc":"Buchantiquariats-Dorf am Fjærlandsfjord.","img":""},
  {"id":62,"name":"Balestrand","lat":61.2062,"lng":6.5277,"type":"village","region":"Vestlandet","desc":"Malerisches Dorf am Sognefjord – beliebt seit dem 19. Jh.","img":""},
  {"id":63,"name":"Aurland","lat":60.9000,"lng":7.1833,"type":"village","region":"Vestlandet","desc":"Ausgangspunkt für Wanderungen zum Aurlandsvangen.","img":""},
  {"id":64,"name":"Lærdal","lat":61.1000,"lng":7.4833,"type":"village","region":"Vestlandet","desc":"Historische Holzhausstadt im Sognefjord – unter UNESCO-Schutz.","img":""},
  {"id":65,"name":"Mundal","lat":61.4100,"lng":6.7500,"type":"village","region":"Vestlandet","desc":"Buchhandlungsdorf am Fjærlandsfjord.","img":""},
  {"id":66,"name":"Gudvangen","lat":60.8733,"lng":6.8333,"type":"village","region":"Vestlandet","desc":"Am Ende des Nærøyfjords – Wikinger-Erlebnisdorf.","img":""},
  {"id":67,"name":"Myrdal","lat":60.7333,"lng":7.0833,"type":"landmark","region":"Vestlandet","desc":"Zugbahnhof auf 866 m – Startpunkt der Flåmsbahn.","img":""},
  {"id":68,"name":"Finse","lat":60.5947,"lng":7.5078,"type":"village","region":"Vestlandet","desc":"Autofreier Bergort auf 1.222 m – Gletscherwanderungen.","img":""},
  {"id":69,"name":"Geilo","lat":60.5333,"lng":8.2000,"type":"city","region":"Vestlandet","desc":"Bekanntes Wintersportgebiet auf der Hardangervidda.","img":""},
  {"id":70,"name":"Numedal","lat":60.2000,"lng":9.1667,"type":"landmark","region":"Østlandet","desc":"Romantisches Tal mit Stabkirchen und alter Bauernkultur.","img":""},
  {"id":71,"name":"Kongsberg","lat":59.6700,"lng":9.6500,"type":"city","region":"Østlandet","desc":"Silberminenstadt – barocke Kirche aus dem 18. Jahrhundert.","img":""},
  {"id":72,"name":"Notodden","lat":59.5600,"lng":9.2600,"type":"city","region":"Østlandet","desc":"Heimat der Heddal-Stabkirche, der größten Norwegens.","img":""},
  {"id":73,"name":"Heddal Stabkirche","lat":59.5608,"lng":9.2103,"type":"landmark","region":"Østlandet","desc":"Größte Stabkirche Norwegens, erbaut um 1150.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Heddal_stave_church_%28cropped%29.jpg/640px-Heddal_stave_church_%28cropped%29.jpg"},
  {"id":74,"name":"Rjukan","lat":59.8800,"lng":8.5900,"type":"city","region":"Østlandet","desc":"Industriestadt im Tinnedalen – UNESCO-Welterbe (Schweres Wasser).","img":""},
  {"id":75,"name":"Gaustatoppen","lat":59.8500,"lng":8.6500,"type":"mountain","region":"Østlandet","desc":"Markanter Berg in Telemark – 1.883 m, von 1/6 Norwegens sichtbar.","img":""},
  {"id":76,"name":"Telemark-Kanal","lat":59.3000,"lng":8.5000,"type":"landmark","region":"Østlandet","desc":"Historisches Kanalwerk aus dem 19. Jh. mit 18 Schleusen.","img":""},
  {"id":77,"name":"Skien","lat":59.2000,"lng":9.6000,"type":"city","region":"Østlandet","desc":"Heimatstadt Henrik Ibsens – größte Stadt in Telemark.","img":""},
  {"id":78,"name":"Porsgrunn","lat":59.1400,"lng":9.6600,"type":"city","region":"Østlandet","desc":"Hafenstadt am Grenlandsfjord.","img":""},
  {"id":79,"name":"Larvik","lat":59.0500,"lng":10.0300,"type":"city","region":"Østlandet","desc":"Küstenstadt in Vestfold – Heimat Thor Heyerdahls.","img":""},
  {"id":80,"name":"Sandefjord","lat":59.1300,"lng":10.2200,"type":"city","region":"Østlandet","desc":"Ehemalige Walfängerstadt in Vestfold.","img":""},
  {"id":81,"name":"Tønsberg","lat":59.2700,"lng":10.4100,"type":"city","region":"Østlandet","desc":"Älteste Stadt Norwegens – Wikingererbe aus dem 9. Jh.","img":""},
  {"id":82,"name":"Horten","lat":59.4200,"lng":10.4900,"type":"city","region":"Østlandet","desc":"Küstenstadt am Oslofjord mit Marinemuseum.","img":""},
  {"id":83,"name":"Halden","lat":59.1200,"lng":11.3900,"type":"city","region":"Østlandet","desc":"Grenzstadt zu Schweden mit der Festung Fredriksten.","img":""},
  {"id":84,"name":"Sarpsborg","lat":59.2900,"lng":11.1100,"type":"city","region":"Østlandet","desc":"Älteste Stadt Ostnorwegens, gegründet 1016 von Olaf dem Heiligen.","img":""},
  {"id":85,"name":"Moss","lat":59.4400,"lng":10.6600,"type":"city","region":"Østlandet","desc":"Industriestadt am Oslofjord mit dem Mossvertrag 1814.","img":""},
  {"id":86,"name":"Lillestrøm","lat":59.9500,"lng":11.0500,"type":"city","region":"Østlandet","desc":"Vorort von Oslo mit großem Messegelände.","img":""},
  {"id":87,"name":"Kongsvinger","lat":60.1900,"lng":12.0100,"type":"city","region":"Østlandet","desc":"Grenzfestung zu Schweden in Innlandet.","img":""},
  {"id":88,"name":"Hamar","lat":60.7939,"lng":11.0678,"type":"city","region":"Innlandet","desc":"Olympiastadt von 1994 am Mjøsa-See.","img":""},
  {"id":89,"name":"Gjøvik","lat":60.7950,"lng":10.6917,"type":"city","region":"Innlandet","desc":"Stadt am Mjøsa – größter Binnensee Norwegens.","img":""},
  {"id":90,"name":"Lillehammer","lat":61.1153,"lng":10.4662,"type":"city","region":"Innlandet","desc":"Olympiastadt 1994 – Wintersportmekka und Maihaugen-Freilichtmuseum.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Lillehammer_sett_fra_Lysgardsbakkene_hopp.jpg/640px-Lillehammer_sett_fra_Lysgardsbakkene_hopp.jpg"},
  {"id":91,"name":"Vinstra","lat":61.5800,"lng":9.7500,"type":"city","region":"Innlandet","desc":"Im Gudbrandsdalen – Heimat von Peer Gynt.","img":""},
  {"id":92,"name":"Otta","lat":61.7728,"lng":9.5361,"type":"city","region":"Innlandet","desc":"Knotenpunkt zwischen Oslo und Bergen/Trondheim.","img":""},
  {"id":93,"name":"Lom","lat":61.8389,"lng":8.5656,"type":"city","region":"Innlandet","desc":"Historische Stabkirche und Tor zum Jotunheimen.","img":""},
  {"id":94,"name":"Lom Stabkirche","lat":61.8389,"lng":8.5656,"type":"landmark","region":"Innlandet","desc":"Eine der schönsten Stabkirchen Norwegens aus dem 12. Jh.","img":""},
  {"id":95,"name":"Røros","lat":62.5744,"lng":11.3839,"type":"city","region":"Trøndelag","desc":"UNESCO-Welterbe – perfekt erhaltene Bergbaustadt aus dem 17. Jh.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Roros_church.jpg/640px-Roros_church.jpg"},
  {"id":96,"name":"Oppdal","lat":62.5950,"lng":9.6900,"type":"city","region":"Trøndelag","desc":"Wintersportort am Dovrefjell – Kreuzungspunkt historischer Routen.","img":""},
  {"id":97,"name":"Sunndalsøra","lat":62.6800,"lng":8.5600,"type":"city","region":"Vestlandet","desc":"Im Sunndalsfjord – einer der schönsten Fjorde des Trøndelags.","img":""},
  {"id":98,"name":"Namsos","lat":64.4670,"lng":11.4940,"type":"city","region":"Trøndelag","desc":"Stadt an der Namsen – Lachsfluss Norwegens.","img":""},
  {"id":99,"name":"Steinkjer","lat":64.0147,"lng":11.4951,"type":"city","region":"Trøndelag","desc":"Verwaltungssitz von Trøndelag.","img":""},
  {"id":100,"name":"Levanger","lat":63.7464,"lng":11.2997,"type":"city","region":"Trøndelag","desc":"Küstenort am Trondheimsfjord.","img":""},
  {"id":101,"name":"Verdal","lat":63.7900,"lng":11.4800,"type":"city","region":"Trøndelag","desc":"Bekannt durch die Stiklestad-Schlachtfelder (1030).","img":""},
  {"id":102,"name":"Stiklestad","lat":63.8431,"lng":11.5050,"type":"landmark","region":"Trøndelag","desc":"Schlachtfeld von 1030 – König Olaf II. fiel hier, später heiliggesprochen.","img":""},
  {"id":103,"name":"Stjørdal","lat":63.4800,"lng":10.8900,"type":"city","region":"Trøndelag","desc":"Stadt nahe Trondheim Airport Værnes.","img":""},
  {"id":104,"name":"Orkanger","lat":63.3100,"lng":9.8500,"type":"city","region":"Trøndelag","desc":"Im Orkafjord, südwestlich von Trondheim.","img":""},
  {"id":105,"name":"Hitra","lat":63.5667,"lng":8.7667,"type":"island","region":"Trøndelag","desc":"Hirsch- und Lachs-Insel im Trøndelags-Schärengarten.","img":""},
  {"id":106,"name":"Frøya","lat":63.7200,"lng":8.6600,"type":"island","region":"Trøndelag","desc":"Atlantikinsel mit weltbekannter Lachsindustrie.","img":""},
  {"id":107,"name":"Kyrksæterøra","lat":63.2800,"lng":9.1000,"type":"village","region":"Trøndelag","desc":"Kleinstadt am Hemnefjord.","img":""},
  {"id":108,"name":"Brønnøysund","lat":65.4743,"lng":12.2131,"type":"city","region":"Nord-Norge","desc":"Stadt an der Helgelandküste – Torghatten in der Nähe.","img":""},
  {"id":109,"name":"Torghatten","lat":65.4378,"lng":12.0928,"type":"landmark","region":"Nord-Norge","desc":"Berg mit natürlichem Loch – legendäre Trollgeschichte.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Torghatten.jpg/640px-Torghatten.jpg"},
  {"id":110,"name":"Sandnessjøen","lat":66.0180,"lng":12.6336,"type":"city","region":"Nord-Norge","desc":"Hauptstadt der Helgelandküste – Sieben Schwestern im Hintergrund.","img":""},
  {"id":111,"name":"Sieben Schwestern","lat":66.0167,"lng":13.0000,"type":"mountain","region":"Nord-Norge","desc":"Markante Bergkette mit sieben Gipfeln auf Alsten.","img":""},
  {"id":112,"name":"Mosjøen","lat":65.8400,"lng":13.1900,"type":"city","region":"Nord-Norge","desc":"Historische Holzbauten am Vefsna-Fluss.","img":""},
  {"id":113,"name":"Polarsirkelsenteret","lat":66.5600,"lng":15.3400,"type":"landmark","region":"Nord-Norge","desc":"Besucherzentrum genau auf dem Polarkreis.","img":""},
  {"id":114,"name":"Fauske","lat":67.2600,"lng":15.3900,"type":"city","region":"Nord-Norge","desc":"Ende der Nordlandsbahn – Ausgangspunkt für Bodø.","img":""},
  {"id":115,"name":"Rognan","lat":67.0800,"lng":15.3900,"type":"village","region":"Nord-Norge","desc":"Im Saltdalen, Tor zum Saltfjellet-Gebirge.","img":""},
  {"id":116,"name":"Sulitjelma","lat":67.1500,"lng":16.0600,"type":"village","region":"Nord-Norge","desc":"Ehemaliger Bergbauort am Fuß des Børvassfjellet.","img":""},
  {"id":117,"name":"Løding","lat":67.3900,"lng":14.7800,"type":"village","region":"Nord-Norge","desc":"Kleines Dorf nahe Bodø am Oslofjord.","img":""},
  {"id":118,"name":"Svolvær","lat":68.2343,"lng":14.5692,"type":"city","region":"Nord-Norge","desc":"Hauptstadt der Lofoten – Ausgangspunkt für Bergwanderungen.","img":""},
  {"id":119,"name":"Kabelvåg","lat":68.2151,"lng":14.4833,"type":"village","region":"Nord-Norge","desc":"Ältestes Städtchen auf den Lofoten.","img":""},
  {"id":120,"name":"Å i Lofoten","lat":67.8817,"lng":12.9831,"type":"village","region":"Nord-Norge","desc":"Letztes Dorf auf den Lofoten – am Ende der E10.","img":""},
  {"id":121,"name":"Nusfjord","lat":68.0358,"lng":13.3183,"type":"village","region":"Nord-Norge","desc":"Besterhaltenstes Fischerdorf auf den Lofoten (UNESCO-Kandidat).","img":""},
  {"id":122,"name":"Svolværgeita","lat":68.2500,"lng":14.5700,"type":"mountain","region":"Nord-Norge","desc":"Berühmter Zwillingsgipfel über Svolvær – Kletterklassiker.","img":""},
  {"id":123,"name":"Andenes","lat":69.3178,"lng":16.1175,"type":"city","region":"Nord-Norge","desc":"Nördlichstes Ende Andøyas – Walbeobachtung und Leuchtturm.","img":""},
  {"id":124,"name":"Nyksund","lat":68.9803,"lng":14.9650,"type":"village","region":"Nord-Norge","desc":"Verlassenes und wiederentdecktes Fischerdorf in Vesterålen.","img":""},
  {"id":125,"name":"Bleik","lat":69.2572,"lng":15.9222,"type":"village","region":"Nord-Norge","desc":"Weißer Sandstrand auf Andøya – beliebt für Papageientaucher.","img":""},
  {"id":126,"name":"Stø","lat":69.0753,"lng":14.9939,"type":"village","region":"Nord-Norge","desc":"Ausgesetztes Fischerdorf in Vesterålen – Wal-Touren.","img":""},
  {"id":127,"name":"Gryllefjord","lat":69.3644,"lng":17.0289,"type":"village","region":"Nord-Norge","desc":"Kleines Dorf auf Senja – Fährverbindung nach Andenes.","img":""},
  {"id":128,"name":"Mefjordvær","lat":69.5072,"lng":17.5081,"type":"village","region":"Nord-Norge","desc":"Romantisches Fischerdorf auf Senja.","img":""},
  {"id":129,"name":"Finnsnes","lat":69.2269,"lng":17.9839,"type":"city","region":"Nord-Norge","desc":"Verwaltungszentrum des Senja-Archipels.","img":""},
  {"id":130,"name":"Lenvik","lat":69.3381,"lng":17.9861,"type":"city","region":"Nord-Norge","desc":"Gemeinde im Herzen des Senja-Archipels.","img":""},
  {"id":131,"name":"Bardufoss","lat":69.0606,"lng":18.5403,"type":"landmark","region":"Nord-Norge","desc":"Militärflugplatz und Wasserfall in Troms.","img":""},
  {"id":132,"name":"Nordreisa","lat":69.9828,"lng":21.0258,"type":"city","region":"Nord-Norge","desc":"Gemeinde in Troms mit dem Reisafjord.","img":""},
  {"id":133,"name":"Reisafjord","lat":70.0000,"lng":20.8000,"type":"fjord","region":"Nord-Norge","desc":"Breiter Fjord in Nord-Troms.","img":""},
  {"id":134,"name":"Kautokeino","lat":69.0161,"lng":23.0447,"type":"city","region":"Nord-Norge","desc":"Sámi-Kulturzentrum in Finnmark – größte Sámi-Gemeinde Norwegens.","img":""},
  {"id":135,"name":"Karasjok","lat":69.4741,"lng":25.5136,"type":"city","region":"Nord-Norge","desc":"Sámi-Parlament und Kulturzentrum – Winkelrekord in Finnmark.","img":""},
  {"id":136,"name":"Kirkenes","lat":69.7267,"lng":30.0511,"type":"city","region":"Nord-Norge","desc":"Grenzstadt zu Russland – Eishotel und Schneemobil-Safari.","img":""},
  {"id":137,"name":"Vardø","lat":70.3714,"lng":31.1100,"type":"city","region":"Nord-Norge","desc":"Östlichste Stadt Norwegens – Hexenprozesse und Festung.","img":""},
  {"id":138,"name":"Vadsø","lat":70.0742,"lng":29.7486,"type":"city","region":"Nord-Norge","desc":"Hauptstadt Finnmarks – finnische Einwandererkultur.","img":""},
  {"id":139,"name":"Berlevåg","lat":70.8578,"lng":29.0906,"type":"city","region":"Nord-Norge","desc":"Ausgesetztes Fischerdorf an der Barentssee.","img":""},
  {"id":140,"name":"Båtsfjord","lat":70.6447,"lng":29.7175,"type":"city","region":"Nord-Norge","desc":"Fischereizentrum in Varanger.","img":""},
  {"id":141,"name":"Mehamn","lat":71.0356,"lng":27.8522,"type":"city","region":"Nord-Norge","desc":"Eine der nördlichsten Gemeinden Finnmarks.","img":""},
  {"id":142,"name":"Gamvik","lat":71.0542,"lng":28.2153,"type":"village","region":"Nord-Norge","desc":"Nördlichstes Fischerdorf des Festlandes.","img":""},
  {"id":143,"name":"Honningsvåg","lat":70.9833,"lng":25.9708,"type":"city","region":"Nord-Norge","desc":"Nächste Stadt zum Nordkapp – Tor zur Nordspitze Europas.","img":""},
  {"id":144,"name":"Gjesvær","lat":71.1333,"lng":25.5000,"type":"village","region":"Nord-Norge","desc":"Kleine Gemeinde auf Magerøya nahe Nordkapp.","img":""},
  {"id":145,"name":"Lakselv","lat":70.0475,"lng":24.9528,"type":"city","region":"Nord-Norge","desc":"Am Porsangerfjord – Lachsfischen im Lakselva.","img":""},
  {"id":146,"name":"Stabbursdalen","lat":70.1833,"lng":25.0667,"type":"nationalpark","region":"Nord-Norge","desc":"Nationalpark mit der nördlichsten Kiefernwaldgrenze der Welt.","img":""},
  {"id":147,"name":"Varangerfjord","lat":70.1000,"lng":29.5000,"type":"fjord","region":"Nord-Norge","desc":"Weitläufiger Fjord in Ostfinnmark – Vogelparadies.","img":""},
  {"id":148,"name":"Ekkerøy","lat":70.0994,"lng":30.1506,"type":"landmark","region":"Nord-Norge","desc":"Küstenkliff – bedeutendes Mövennistgebiet in Varanger.","img":""},
  {"id":149,"name":"Hamningberg","lat":70.5772,"lng":31.0756,"type":"village","region":"Nord-Norge","desc":"Verlassenes Fischerdorf an der Barentssee – Geisterort.","img":""},
  {"id":150,"name":"Øvre Pasvik","lat":69.4000,"lng":28.9333,"type":"nationalpark","region":"Nord-Norge","desc":"Wildester Nationalpark Norwegens – Braunbären und Wölfe.","img":""},
  {"id":151,"name":"Vinger","lat":60.2700,"lng":12.0400,"type":"landmark","region":"Østlandet","desc":"Historische Festung nahe Kongsvinger.","img":""},
  {"id":152,"name":"Elverum","lat":60.8800,"lng":11.5600,"type":"city","region":"Innlandet","desc":"Waldhauptstadt Norwegens – Norsk Skogmuseum.","img":""},
  {"id":153,"name":"Åmot","lat":61.0200,"lng":11.1600,"type":"city","region":"Innlandet","desc":"Im Østerdalen – Militärstadt Rena.","img":""},
  {"id":154,"name":"Rendalen","lat":61.6833,"lng":10.8167,"type":"village","region":"Innlandet","desc":"Großgemeinde im Østerdalen mit Rennfjell.","img":""},
  {"id":155,"name":"Folldal","lat":62.1300,"lng":9.9900,"type":"village","region":"Innlandet","desc":"Ehemaliger Kupferminen-Ort am Dovrefjell.","img":""},
  {"id":156,"name":"Tynset","lat":62.2800,"lng":10.7800,"type":"city","region":"Innlandet","desc":"Hauptort im Norddalen – kälteste bewohnte Region Norwegens.","img":""},
  {"id":157,"name":"Alvdal","lat":62.1133,"lng":10.6139,"type":"village","region":"Innlandet","desc":"Im Østerdalen zwischen Tynset und Folldal.","img":""},
  {"id":158,"name":"Tolga","lat":62.3936,"lng":10.8847,"type":"village","region":"Innlandet","desc":"Im Horndalen – Geburtsort des Komponisten Ole Bull.","img":""},
  {"id":159,"name":"Os","lat":62.5028,"lng":11.2164,"type":"village","region":"Innlandet","desc":"Grenzgemeinde zu Røros – bekannte Volkskunst.","img":""},
  {"id":160,"name":"Kvikne","lat":62.5833,"lng":10.0000,"type":"village","region":"Innlandet","desc":"Abgelegene Gemeinde an der Grenze zu Trøndelag.","img":""},
  {"id":161,"name":"Dombås","lat":62.0742,"lng":9.1236,"type":"city","region":"Innlandet","desc":"Knotenpunkt der Dovre- und Raumabahn.","img":""},
  {"id":162,"name":"Hjerkinn","lat":62.2247,"lng":9.5542,"type":"village","region":"Innlandet","desc":"Hochplateau im Dovrefjell – Moschusochsen-Safaris.","img":""},
  {"id":163,"name":"Kongsvoll","lat":62.3000,"lng":9.6500,"type":"landmark","region":"Innlandet","desc":"Historisches Fjellstue (Berghotel) auf der alten Pilgrimroute.","img":""},
  {"id":164,"name":"Lesja","lat":62.1200,"lng":8.8600,"type":"village","region":"Innlandet","desc":"Im Lesjadalen – Grenze zwischen Ost und West.","img":""},
  {"id":165,"name":"Vagamo","lat":61.8700,"lng":9.1100,"type":"city","region":"Innlandet","desc":"Im Gudbrandsdalen zwischen Dombås und Otta.","img":""},
  {"id":166,"name":"Ringebu","lat":61.5300,"lng":10.1700,"type":"city","region":"Innlandet","desc":"Stabkirche aus dem Mittelalter in Gudbrandsdalen.","img":""},
  {"id":167,"name":"Fåberg","lat":61.1000,"lng":10.5200,"type":"village","region":"Innlandet","desc":"Vorort von Lillehammer am Mjøsa.","img":""},
  {"id":168,"name":"Moelv","lat":60.9400,"lng":10.7000,"type":"city","region":"Innlandet","desc":"Am südlichen Mjøsa-Ufer.","img":""},
  {"id":169,"name":"Brumunddal","lat":60.8800,"lng":10.9400,"type":"city","region":"Innlandet","desc":"Obstbauregion am Mjøsa.","img":""},
  {"id":170,"name":"Stange","lat":60.7200,"lng":11.1800,"type":"city","region":"Innlandet","desc":"Landwirtschaftsgemeinde am Mjøsa.","img":""},
  {"id":171,"name":"Eidsvoll","lat":60.3200,"lng":11.2600,"type":"city","region":"Innlandet","desc":"Geburtsort der Norwegischen Verfassung von 1814.","img":""},
  {"id":172,"name":"Minnesund","lat":60.3900,"lng":11.1700,"type":"village","region":"Innlandet","desc":"Nördlichster Punkt des Vororten Oslos am Mjøsa.","img":""},
  {"id":173,"name":"Nannestad","lat":60.2300,"lng":11.0700,"type":"city","region":"Innlandet","desc":"Gartnergemeinde nördlich von Oslo.","img":""},
  {"id":174,"name":"Jessheim","lat":60.1500,"lng":11.1800,"type":"city","region":"Innlandet","desc":"Dicht besiedelte Stadt nahe Oslo Airport Gardermoen.","img":""},
  {"id":175,"name":"Gardermoen","lat":60.1939,"lng":11.1004,"type":"landmark","region":"Innlandet","desc":"Norwegens größter Flughafen – Hauptdrehkreuz des Landes.","img":""},
  {"id":176,"name":"Nittedal","lat":60.0700,"lng":10.8800,"type":"city","region":"Innlandet","desc":"Waldgemeinde nördlich von Oslo.","img":""},
  {"id":177,"name":"Lørenskog","lat":59.9200,"lng":10.9900,"type":"city","region":"Innlandet","desc":"Vorort östlich von Oslo.","img":""},
  {"id":178,"name":"Ski","lat":59.7200,"lng":10.8300,"type":"city","region":"Innlandet","desc":"Pendlerstadt südlich von Oslo.","img":""},
  {"id":179,"name":"Ås","lat":59.6600,"lng":10.7900,"type":"city","region":"Innlandet","desc":"Universitätsstadt (NMBU) südlich von Oslo.","img":""},
  {"id":180,"name":"Drøbak","lat":59.6600,"lng":10.6300,"type":"city","region":"Innlandet","desc":"Weihnachtsdorf am Oslofjord – Weihnachtsmann-Postamt.","img":""},
  {"id":181,"name":"Nesodden","lat":59.7700,"lng":10.6400,"type":"city","region":"Innlandet","desc":"Halbinsel im Oslofjord – natürliches Ausflugsziel für Oslo.","img":""},
  {"id":182,"name":"Bærum","lat":59.9000,"lng":10.5300,"type":"city","region":"Innlandet","desc":"Wohlhabendste Gemeinde Norwegens, westlich von Oslo.","img":""},
  {"id":183,"name":"Asker","lat":59.8300,"lng":10.4400,"type":"city","region":"Innlandet","desc":"Küstenort am Oslofjord, beliebter Wohnvorort Oslos.","img":""},
  {"id":184,"name":"Røyken","lat":59.7400,"lng":10.3900,"type":"city","region":"Innlandet","desc":"Am Westufer des Oslofjords.","img":""},
  {"id":185,"name":"Lier","lat":59.7900,"lng":10.2400,"type":"city","region":"Innlandet","desc":"Obstbaugemeinde zwischen Oslo und Drammen.","img":""},
  {"id":186,"name":"Hokksund","lat":59.7700,"lng":9.9200,"type":"city","region":"Innlandet","desc":"Im Numedal – am Beginn des Telemarkkanals.","img":""},
  {"id":187,"name":"Jevnaker","lat":60.2400,"lng":10.3700,"type":"city","region":"Innlandet","desc":"Glasblaserei Hadeland – historische Glashütte seit 1762.","img":""},
  {"id":188,"name":"Hønefoss","lat":60.1700,"lng":10.2600,"type":"city","region":"Innlandet","desc":"Hauptstadt von Ringerike – größter Wasserfall Ostnorwegens.","img":""},
  {"id":189,"name":"Tyrifjorden","lat":60.0800,"lng":10.1500,"type":"landmark","region":"Innlandet","desc":"Norways fünftgrößter See – Vogelparadies in Viken.","img":""},
  {"id":190,"name":"Krøderen","lat":60.2400,"lng":9.7200,"type":"village","region":"Innlandet","desc":"Touristensee in Numedal.","img":""},
  {"id":191,"name":"Nore og Uvdal","lat":60.2400,"lng":9.0600,"type":"village","region":"Innlandet","desc":"In Numedal – Stabkirchen und Hydrozentrale.","img":""},
  {"id":192,"name":"Veggli","lat":60.0200,"lng":9.1900,"type":"village","region":"Innlandet","desc":"Kleines Dorf in Numedal.","img":""},
  {"id":193,"name":"Uvdal","lat":60.2833,"lng":8.9500,"type":"village","region":"Innlandet","desc":"Abgelegene Hochgebirgsregion in Numedal.","img":""},
  {"id":194,"name":"Dagali","lat":60.4400,"lng":8.5800,"type":"village","region":"Innlandet","desc":"Auf der Hardangervidda – Grenze zu Vestland.","img":""},
  {"id":195,"name":"Norefjell","lat":60.3200,"lng":9.5200,"type":"mountain","region":"Innlandet","desc":"Skigebiet östlich von Numedal – Panoramaaussicht.","img":""},
  {"id":196,"name":"Kongsberg Grube","lat":59.6500,"lng":9.6500,"type":"landmark","region":"Østlandet","desc":"Silberminenmuseum – größte Silberminen Europas (17.-19. Jh.).","img":""},
  {"id":197,"name":"Lardal","lat":59.3300,"lng":9.8800,"type":"village","region":"Østlandet","desc":"Im Telemark-Hinterland.","img":""},
  {"id":198,"name":"Kviteseid","lat":59.3900,"lng":8.4900,"type":"village","region":"Østlandet","desc":"Im Kviteseiddalen – Landschaftsgebiet Telemarks.","img":""},
  {"id":199,"name":"Dalen","lat":59.4400,"lng":8.0000,"type":"village","region":"Østlandet","desc":"Am Ende des Telemarkkanals – Jugendstil-Hotel aus 1894.","img":""},
  {"id":200,"name":"Åmli","lat":58.9200,"lng":8.5300,"type":"village","region":"Sørlandet","desc":"Im Aust-Agder-Hinterland.","img":""},
  {"id":201,"name":"Evje","lat":58.5900,"lng":7.8100,"type":"city","region":"Sørlandet","desc":"Abenteuerpark und Mineralienmuseum in Setesdal.","img":""},
  {"id":202,"name":"Byglandsfjord","lat":58.6800,"lng":7.7900,"type":"village","region":"Sørlandet","desc":"Am gleichnamigen See im Setesdal.","img":""},
  {"id":203,"name":"Valle","lat":59.2100,"lng":7.5500,"type":"village","region":"Sørlandet","desc":"Kulturzentrum des Setesdals.","img":""},
  {"id":204,"name":"Bykle","lat":59.4400,"lng":7.3200,"type":"village","region":"Sørlandet","desc":"Nördlichste Gemeinde Aust-Agders.","img":""},
  {"id":205,"name":"Hovden","lat":59.5500,"lng":7.3700,"type":"village","region":"Sørlandet","desc":"Skigebiet am Byklefjell – höchste Skistation Sørlandet.","img":""},
  {"id":206,"name":"Mandal","lat":58.0300,"lng":7.4600,"type":"city","region":"Sørlandet","desc":"Südlichste Stadt Norwegens – schöner Sandstrand.","img":""},
  {"id":207,"name":"Farsund","lat":58.0900,"lng":6.7900,"type":"city","region":"Sørlandet","desc":"Listalandet – Vogelparadies und Festung Christiansholm.","img":""},
  {"id":208,"name":"Lyngdal","lat":58.1400,"lng":7.0800,"type":"city","region":"Sørlandet","desc":"Küstenort in Vest-Agder.","img":""},
  {"id":209,"name":"Flekkefjord","lat":58.2900,"lng":6.6600,"type":"city","region":"Sørlandet","desc":"Holländerstadt am Flekkefjord mit charakteristischem Stadtbild.","img":""},
  {"id":210,"name":"Egersund","lat":58.4500,"lng":6.0000,"type":"city","region":"Vestlandet","desc":"Fischereizentrum an der Jæren-Küste.","img":""},
  {"id":211,"name":"Lysefjord-Kjerag","lat":59.0367,"lng":6.5769,"type":"landmark","region":"Vestlandet","desc":"Kjeragbolten – Felsblock in einer Felsspalte über dem Lysefjord.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Kjeragbolten_Aug2008.jpg/640px-Kjeragbolten_Aug2008.jpg"},
  {"id":212,"name":"Suldal","lat":59.5400,"lng":6.3600,"type":"village","region":"Vestlandet","desc":"Im Suldalslågen – Lachsrevier und Sand Lachs Museum.","img":""},
  {"id":213,"name":"Sauda","lat":59.6500,"lng":6.3600,"type":"city","region":"Vestlandet","desc":"Industrie- und Wandergebiet im Ryfylke.","img":""},
  {"id":214,"name":"Odda","lat":60.0700,"lng":6.5500,"type":"city","region":"Vestlandet","desc":"Am Ende des Sørfjords – Ausgangspunkt zum Trolltunga.","img":""},
  {"id":215,"name":"Rosendal","lat":59.9900,"lng":6.0200,"type":"village","region":"Vestlandet","desc":"Einziger Baronie Norwegens – romantisches Schloss.","img":""},
  {"id":216,"name":"Norheimsund","lat":60.3700,"lng":5.9800,"type":"village","region":"Vestlandet","desc":"Am Hardangerfjord – Ausgangspunkt für Fjordwanderungen.","img":""},
  {"id":217,"name":"Kvam","lat":60.3900,"lng":6.1600,"type":"village","region":"Vestlandet","desc":"Im Hardangerfjord – Obstgärten und Wasserfälle.","img":""},
  {"id":218,"name":"Ullensvang","lat":60.3100,"lng":6.6800,"type":"village","region":"Vestlandet","desc":"Berühmter Obstbezirk am Hardangerfjord.","img":""},
  {"id":219,"name":"Lofthus","lat":60.3100,"lng":6.6500,"type":"village","region":"Vestlandet","desc":"Malerisches Obstbauerndorf am Sørfjord.","img":""},
  {"id":220,"name":"Kinsarvik","lat":60.3700,"lng":6.7200,"type":"village","region":"Vestlandet","desc":"Historische Stabkirche aus dem 12. Jh. im Hardangerfjord.","img":""},
  {"id":221,"name":"Jondal","lat":60.2400,"lng":6.3400,"type":"village","region":"Vestlandet","desc":"Ruhiges Dorf am Hardangerfjord.","img":""},
  {"id":222,"name":"Rosendal Baroni","lat":59.9900,"lng":6.0100,"type":"landmark","region":"Vestlandet","desc":"Einzige Baronie Norwegens mit Renaissance-Schloss (1665).","img":""},
  {"id":223,"name":"Folgefonna","lat":60.0500,"lng":6.3700,"type":"nationalpark","region":"Vestlandet","desc":"Dritttgrößter Gletscher Norwegens – Sommerskifahren.","img":""},
  {"id":224,"name":"Stord","lat":59.7800,"lng":5.4900,"type":"city","region":"Vestlandet","desc":"Insel in Sunnhordland – Schiffbau und Offshore-Industrie.","img":""},
  {"id":225,"name":"Haugesund","lat":59.4133,"lng":5.2686,"type":"city","region":"Vestlandet","desc":"Filmfestivalstadt und Ausgangspunkt des Norges-Küstenwegs.","img":""},
  {"id":226,"name":"Karmøy","lat":59.2900,"lng":5.2600,"type":"island","region":"Vestlandet","desc":"Großinsel in Rogaland – Wikingergeschichte und Industrie.","img":""},
  {"id":227,"name":"Avaldsnes","lat":59.3600,"lng":5.2600,"type":"landmark","region":"Vestlandet","desc":"Wikingerkönigsgeschichte – Steinkirche und Olavssäule.","img":""},
  {"id":228,"name":"Tananger","lat":58.9400,"lng":5.5700,"type":"village","region":"Vestlandet","desc":"Kleiner Fischerort und Offshore-Basis bei Stavanger.","img":""},
  {"id":229,"name":"Sola","lat":58.8800,"lng":5.6300,"type":"city","region":"Vestlandet","desc":"Langes Sandstrand bei Stavanger – Flughafen Sola.","img":""},
  {"id":230,"name":"Randaberg","lat":59.0000,"lng":5.6100,"type":"city","region":"Vestlandet","desc":"Kleine Gemeinde nördlich von Stavanger.","img":""},
  {"id":231,"name":"Rennesøy","lat":59.0800,"lng":5.6900,"type":"island","region":"Vestlandet","desc":"Insel im Boknafjord nahe Stavanger.","img":""},
  {"id":232,"name":"Finnøy","lat":59.1500,"lng":5.8100,"type":"island","region":"Vestlandet","desc":"Inselgemeinde im Ryfylke.","img":""},
  {"id":233,"name":"Jelsa","lat":59.5500,"lng":5.9800,"type":"village","region":"Vestlandet","desc":"Im Saudasfjord – Ryfylke-Gebirge.","img":""},
  {"id":234,"name":"Hjelmeland","lat":59.2300,"lng":6.1600,"type":"village","region":"Vestlandet","desc":"Im Jøsenfjord – ruhiges Fjordleben.","img":""},
  {"id":235,"name":"Forsand","lat":58.9000,"lng":6.1300,"type":"village","region":"Vestlandet","desc":"Tor zum Lysefjord – Ausgangspunkt Preikestolen-Wanderung.","img":""},
  {"id":236,"name":"Frafjord","lat":58.9500,"lng":6.2200,"type":"fjord","region":"Vestlandet","desc":"Fjord im Inneren des Lysefjords.","img":""},
  {"id":237,"name":"Årdal","lat":61.2400,"lng":7.7100,"type":"city","region":"Vestlandet","desc":"Am Ende des Sognefjords – Aluminiumindustrie.","img":""},
  {"id":238,"name":"Jostedalen","lat":61.6700,"lng":7.2500,"type":"valley","region":"Vestlandet","desc":"Tal mit direktem Zugang zum Jostedalsbreen.","img":""},
  {"id":239,"name":"Skjolden","lat":61.4900,"lng":7.5900,"type":"village","region":"Vestlandet","desc":"Am Ende des Lusterfjords – Wittgenstein lebte hier.","img":""},
  {"id":240,"name":"Urnes Stabkirche","lat":61.3000,"lng":7.3100,"type":"landmark","region":"Vestlandet","desc":"UNESCO-Welterbe – älteste erhaltene Stabkirche Norwegens.","img":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Urnes_Stavkirke.jpg/640px-Urnes_Stavkirke.jpg"},
  {"id":241,"name":"Hafslo","lat":61.3700,"lng":7.2300,"type":"village","region":"Vestlandet","desc":"Im Lusterfjord – Obstgärten und mittelalterliche Kirche.","img":""},
  {"id":242,"name":"Solvorn","lat":61.3100,"lng":7.2900,"type":"village","region":"Vestlandet","desc":"Idyllisches Dorf am Lustrafjord gegenüber Urnes.","img":""},
  {"id":243,"name":"Gaupne","lat":61.4100,"lng":7.2700,"type":"village","region":"Vestlandet","desc":"Hauptort in Luster – Tor zum Jostedalsbreen.","img":""},
  {"id":244,"name":"Veitastrond","lat":61.5300,"lng":7.0400,"type":"valley","region":"Vestlandet","desc":"Abgelegenes Tal in Luster – Kraftwerk und Naturreserve.","img":""},
  {"id":245,"name":"Sogndal","lat":61.2269,"lng":7.0956,"type":"city","region":"Vestlandet","desc":"Studentenstadt am Sognefjord.","img":""},
  {"id":246,"name":"Kaupanger","lat":61.1900,"lng":7.2300,"type":"village","region":"Vestlandet","desc":"Stabkirche und Fährverbindung über den Sognefjord.","img":""},
  {"id":247,"name":"Leikanger","lat":61.1800,"lng":6.8100,"type":"village","region":"Vestlandet","desc":"Verwaltungszentrum von Vestland – Obstgärten.","img":""},
  {"id":248,"name":"Hermansverk","lat":61.1800,"lng":6.8400,"type":"village","region":"Vestlandet","desc":"Am Sognefjord – Fährverbindung.","img":""},
  {"id":249,"name":"Vik","lat":61.0800,"lng":6.5800,"type":"village","region":"Vestlandet","desc":"Im Vikøyri – mittelalterliche Stabkirche Hopperstad.","img":""},
  {"id":250,"name":"Hopperstad Stabkirche","lat":61.0750,"lng":6.5790,"type":"landmark","region":"Vestlandet","desc":"Gut erhaltene Stabkirche aus dem 12. Jahrhundert.","img":""},
  {"id":251,"name":"Fresvik","lat":61.0200,"lng":6.7100,"type":"village","region":"Vestlandet","desc":"Kleines Dorf am Sognefjord.","img":""},
  {"id":252,"name":"Vangsnes","lat":61.1700,"lng":6.6500,"type":"village","region":"Vestlandet","desc":"Wikingerstatue Fridtjof am Sognefjord.","img":""},
  {"id":253,"name":"Vik Stabkirche","lat":61.0800,"lng":6.5700,"type":"landmark","region":"Vestlandet","desc":"Kirchensiedlung aus dem Mittelalter.","img":""},
  {"id":254,"name":"Lavik","lat":61.1000,"lng":5.5700,"type":"village","region":"Vestlandet","desc":"Fährverbindung über den Sognefjord.","img":""},
  {"id":255,"name":"Eivindvik","lat":60.9600,"lng":5.1900,"type":"village","region":"Vestlandet","desc":"Historisches Kirchengebiet in Gulen.","img":""},
  {"id":256,"name":"Dale","lat":60.9700,"lng":5.7700,"type":"village","region":"Vestlandet","desc":"In Dale – alte Textilfabrik und Dorfcharme.","img":""},
  {"id":257,"name":"Masfjorden","lat":60.8800,"lng":5.4600,"type":"fjord","region":"Vestlandet","desc":"Ruhiger Fjord östlich von Bergen.","img":""},
  {"id":258,"name":"Modalen","lat":60.8300,"lng":5.8800,"type":"village","region":"Vestlandet","desc":"Kleinste Gemeinde Norwegens – Mofjell und Wasserfall.","img":""},
  {"id":259,"name":"Vaksdal","lat":60.4800,"lng":5.7300,"type":"village","region":"Vestlandet","desc":"Im Bergsdalen – historische Textilindustrie.","img":""},
  {"id":260,"name":"Osterøy","lat":60.5500,"lng":5.5800,"type":"island","region":"Vestlandet","desc":"Größte Binneninsel Norwegens östlich von Bergen.","img":""},
  {"id":261,"name":"Os","lat":60.1900,"lng":5.4700,"type":"city","region":"Vestlandet","desc":"Vorort von Bergen – traditionelles Landschaftsbild.","img":""},
  {"id":262,"name":"Fusa","lat":60.2400,"lng":5.6300,"type":"village","region":"Vestlandet","desc":"Im Fusafjord südlich von Bergen.","img":""},
  {"id":263,"name":"Tysnes","lat":59.9500,"lng":5.6000,"type":"island","region":"Vestlandet","desc":"Insel im Hardangerfjord – Lachszucht und Obstgärten.","img":""},
  {"id":264,"name":"Fitjar","lat":59.9200,"lng":5.3300,"type":"city","region":"Vestlandet","desc":"Geburtssort König Håkons des Guten – Sunnhordland.","img":""},
  {"id":265,"name":"Bømlo","lat":59.7800,"lng":5.2300,"type":"island","region":"Vestlandet","desc":"Insel in Sunnhordland – wichtige Fischerei und Kultivierungsgebiet.","img":""},
  {"id":266,"name":"Espevær","lat":59.6200,"lng":5.1600,"type":"village","region":"Vestlandet","desc":"Historisches Fischereimuseum auf einer Insel in Bømlo.","img":""},
  {"id":267,"name":"Utsira","lat":59.3000,"lng":4.8800,"type":"island","region":"Vestlandet","desc":"Kleinste Gemeinde Nordsees – westlichste bewohnte Insel Norwegens.","img":""},
  {"id":268,"name":"Fedje","lat":60.7700,"lng":4.7200,"type":"island","region":"Vestlandet","desc":"Westlichste bewohnte Insel Hordalands.","img":""},
  {"id":269,"name":"Askøy","lat":60.4300,"lng":5.1700,"type":"island","region":"Vestlandet","desc":"Hauptvorort Bergens auf einer Insel.","img":""},
  {"id":270,"name":"Øygarden","lat":60.5200,"lng":4.8700,"type":"city","region":"Vestlandet","desc":"Inselgemeinde außerhalb Bergens – Schärengarten.","img":""},
  {"id":271,"name":"Sotra","lat":60.3500,"lng":5.0400,"type":"island","region":"Vestlandet","desc":"Zwei Inseln vor Bergen – Küstenwandern und Fischen.","img":""},
  {"id":272,"name":"Fjell","lat":60.3700,"lng":5.0900,"type":"city","region":"Vestlandet","desc":"Gemeinde auf Sotra – beliebter Wohnort nahe Bergen.","img":""},
  {"id":273,"name":"Sund","lat":60.2500,"lng":5.0500,"type":"city","region":"Vestlandet","desc":"Im äußeren Archipel von Bergen.","img":""},
  {"id":274,"name":"Austevoll","lat":60.0900,"lng":5.2600,"type":"island","region":"Vestlandet","desc":"Inselgruppe südlich von Bergen – Lachs und Schiffe.","img":""},
  {"id":275,"name":"Tysfjord","lat":68.1000,"lng":16.3500,"type":"fjord","region":"Nord-Norge","desc":"Einer der tiefsten Fjorde Norwegens – Orca-Beobachtungen im Winter.","img":""},
  {"id":276,"name":"Steigen","lat":67.8700,"lng":15.5000,"type":"village","region":"Nord-Norge","desc":"Ruhige Halbinsel nördlich von Bodø.","img":""},
  {"id":277,"name":"Gildeskål","lat":67.0000,"lng":14.0000,"type":"village","region":"Nord-Norge","desc":"Historische Kirchengemeinde in Nordland.","img":""},
  {"id":278,"name":"Rødøy","lat":66.6900,"lng":13.6200,"type":"island","region":"Nord-Norge","desc":"Insel in Nordland – Rødøyløva-Bergmassiv.","img":""},
  {"id":279,"name":"Lurøy","lat":66.4200,"lng":12.9400,"type":"village","region":"Nord-Norge","desc":"Inselgemeinde mit dem Træna-Archipel in der Nähe.","img":""},
  {"id":280,"name":"Træna","lat":66.5200,"lng":12.1100,"type":"island","region":"Nord-Norge","desc":"Westlichster Archipel Nordlands – international bekanntes Musikfestival.","img":""},
  {"id":281,"name":"Herøy","lat":66.1500,"lng":13.0800,"type":"island","region":"Nord-Norge","desc":"Insel in Helgeland – Fischerei und Küstentourismus.","img":""},
  {"id":282,"name":"Dønna","lat":66.1000,"lng":12.5000,"type":"island","region":"Nord-Norge","desc":"Insel in Helgeland mit schönem Aussicht auf Sieben Schwestern.","img":""},
  {"id":283,"name":"Leka","lat":65.1100,"lng":11.6400,"type":"island","region":"Trøndelag","desc":"Geoparkfels-Insel in Nord-Trøndelag.","img":""},
  {"id":284,"name":"Nærøysund","lat":64.8700,"lng":11.3500,"type":"landmark","region":"Trøndelag","desc":"Enge Meerenge in Nord-Trøndelag – Vogelparadies.","img":""},
  {"id":285,"name":"Kolvereid","lat":64.8600,"lng":11.5900,"type":"city","region":"Trøndelag","desc":"Hauptort in Nærøy – Verwaltungszentrum.","img":""},
  {"id":286,"name":"Bindal","lat":65.1400,"lng":12.3700,"type":"village","region":"Trøndelag","desc":"Südlichste Gemeinde Nordlands – Küsten- und Fjordlandschaft.","img":""},
  {"id":287,"name":"Grong","lat":64.4700,"lng":12.3100,"type":"city","region":"Trøndelag","desc":"Im Namsen-Tal – bekannte Lachsfischerei.","img":""},
  {"id":288,"name":"Lierne","lat":64.3700,"lng":13.7200,"type":"village","region":"Trøndelag","desc":"Waldgemeinde an der schwedischen Grenze.","img":""},
  {"id":289,"name":"Røyrvik","lat":64.8800,"lng":13.5700,"type":"village","region":"Trøndelag","desc":"Abgelegene Gemeinde in Namdalen.","img":""},
  {"id":290,"name":"Snåsa","lat":64.2400,"lng":12.3800,"type":"city","region":"Trøndelag","desc":"Sámi-Gemeinde am Snåsavatnet – größter See Trøndelags.","img":""},
  {"id":291,"name":"Inderøy","lat":63.9800,"lng":11.1600,"type":"city","region":"Trøndelag","desc":"Am Trondheimsfjord – Goldene Straße historischer Stätten.","img":""},
  {"id":292,"name":"Mosvik","lat":63.8600,"lng":11.0000,"type":"village","region":"Trøndelag","desc":"Halbinsel im Trondheimsfjord.","img":""},
  {"id":293,"name":"Leksvik","lat":63.6700,"lng":10.6200,"type":"village","region":"Trøndelag","desc":"Halbinsel Fosen westlich des Trondheimsfjords.","img":""},
  {"id":294,"name":"Rissa","lat":63.5800,"lng":10.1200,"type":"city","region":"Trøndelag","desc":"Im Trondheimsfjord-Hinterland – Naturkatastrophe 1978.","img":""},
  {"id":295,"name":"Ørland","lat":63.7000,"lng":9.6100,"type":"city","region":"Trøndelag","desc":"Militärflugplatz und Naturschutzgebiet auf Fosen.","img":""},
  {"id":296,"name":"Bjugn","lat":63.7600,"lng":9.7000,"type":"city","region":"Trøndelag","desc":"Küstenort auf Fosen – Solund-Arkeologisches Museum.","img":""},
  {"id":297,"name":"Agdenes","lat":63.5200,"lng":9.6800,"type":"village","region":"Trøndelag","desc":"Am Trondheimsfjord-Eingang – historische Festung.","img":""},
  {"id":298,"name":"Hemne","lat":63.0800,"lng":9.6800,"type":"village","region":"Trøndelag","desc":"Im Hemnefjord – Industrie und Fischerei.","img":""},
  {"id":299,"name":"Surnadal","lat":62.9800,"lng":8.7000,"type":"city","region":"Vestlandet","desc":"Im Surnadalen – am Ende des Vinjefjords.","img":""},
  {"id":300,"name":"Halsa","lat":63.0900,"lng":8.2400,"type":"village","region":"Vestlandet","desc":"Kleine Gemeinde am Vinjefjord.","img":""}
]
